apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: emall
spec:
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8081
  selector:
    app: client-service
  type: NodePort
