apiVersion: v1
kind: Service
metadata:
  name: e-mall-db
  namespace: emall
spec:
  ports:
    - protocol: "TCP"
      port: 5432
      targetPort: 5432
  selector:
    app: e-mall-db
  type: NodePort
