apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: emall
spec:
  ports:
    - protocol: "TCP"
      name: "9092"
      port: 9092
      targetPort: 9092
    - protocol: "TCP"
      name: "29092"
      port: 29092
      targetPort: 29092
  selector:
    app: kafka
  type: NodePort
