apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: emall
spec:
  ports:
    - protocol: "TCP"
      port: 8082
      targetPort: 8082
  selector:
    app: order-service
  type: NodePort
