server:
  port: 8082
  servlet:
    contextPath: /order/api

spring:
  application:
    name: order-service
  data:
    mongodb:
      authentication-database: admin
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      database: ${MONGO_DB}
      port: ${MONGO_PORT}
      host: ${MONGO_HOST}
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://e-mall-db:5432/${POSTGRES_DB}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: off
  springdoc:
    swagger-ui:
      use-root-path: true
      tags-sorter: alpha
      operations-sorter: alpha
  cloud:
    compatibility-verifier:
      enabled: false
  kafka:
    bootstrap-servers: kafka:9092
    group-id: ${ORDER_KAFKA_GROUP}
    consumer:
      properties:
        isolation:
          level: ${ORDER_KAFKA_CONSUMER_ISOLATION_LEVEL}
        spring:
          json:
            trusted:
              packages: "*"
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    hostname: localhost
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always