server:
  port: 8082
  servlet:
    contextPath: /order/api

spring:
  application:
    name: order-service
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://e-mall_db:5432/e-mall
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: off
  springdoc:
    swagger-ui:
      path: /swagger-ui
      tags-sorter: alpha
      operations-sorter: alpha
  cloud:
    compatibility-verifier:
      enabled: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    hostname: localhost
    preferIpAddress: true