version: '1'
services:
  e-mall_db:
    image: e-mall_db
    ports:
      - "5432:5432"
  client-service:
    depends_on:
      - e-mall_db
    image: client-service-image
    ports:
      - "8081:8081"
  order-service:
    depends_on:
      - e-mall_db
    image: order-service-image
    ports:
      - "8082:8082"
  eureka-server:
    image: eureka-server-image
    ports:
      - "8761:8761"