server:
  port: 8082
  servlet:
    contextPath: /order/api

spring:
  application:
    name: order-service
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5433/e-mall
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: off
  springdoc:
    swagger-ui:
      path: /swagger-ui
      tags-sorter: alpha
      operations-sorter: alpha

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
    preferIpAddress: true