server:
  port: 8081
  servlet:
    contextPath: /client/api

spring:
  application:
    name: client-service
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://e-mall-db:5432/e-mall
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: off
  springdoc:
    swagger-ui:
      use-root-path: true
      tags-sorter: alpha
      operations-sorter: alpha
  cloud:
    compatibility-verifier:
      enabled: false
  kafka:
    bootstrap-servers: kafka:9092
    group-id: orderGroup
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    hostname: localhost
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

